services:
  # postgres:
  #   image: postgres:12
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  mongodb:
    image: mongo:6.0.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

  weapi-service:
    build: src/weapi-service
    container_name: weapi-service
    restart: always
    ports:
      - 3001:3001
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-O",
          "/dev/null",
          "-q",
          "http://weapi-service:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - WEATHER_DB_NAME=weather_db
      - WEATHER_DB_COLLECTION_NAME=weather_data
      - WEATHER_DB_URI=mongodb://mongo:27017/weather_db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend_services

networks:
  backend_services:
    driver: bridge
