version: "3.7"
services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - home-system

networks:
  home-system:
    name: home-system
    external: true
